#!/bin/bash
# linkit
# linking script
# 2015-06-20 15:35:12

if [ $1 ]
then
  BASE_DIR=~/code/scripts
  DIR=$BASE_DIR$1
  LINK=$BASE_DIR/$1
  APP_NAME=$1
  if [ -d "$LINK" ]; then
    # Control will enter here if $DIRECTORY exists
    echo "Directory ${DIR} exist. Choose a different name"
    exit
  else
    read -p "Are you sure you want to create the hard link? [yY]" -n 1 -r
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
	    echo  "linking..."
	    ln $1 $LINK
	 else
		echo
		echo "Second thougts eh? at $(date)"
		exit
	fi
  fi
else  
  echo "Destination link name is null, leaving the script"
  exit
fi
